### ISSUE TITLE
no need for a bin

### ISSUE THREAD

**Issue by ghost** [node-browser-compat/btoa#3]
When I try and do `npm install btoa`, NPM (on Linux) complains and gives me the following error:

```
npm WARN package.json bootstrap-ch@3.1.0 No repository field.
npm WARN package.json canonical-json@0.0.3 No repository field.
npm http GET https://registry.npmjs.org/btoa/1.1.1
npm http 304 https://registry.npmjs.org/btoa/1.1.1
npm ERR! Error: EROFS, symlink '../btoa/bin/btoa.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "btoa"
npm ERR! cwd /media/sf_dev/CHOUI
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path ../btoa/bin/btoa.js
npm ERR! code EROFS
npm ERR! errno 56
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /media/sf_dev/CHOUI/npm-debug.log
npm ERR! not ok code 0
```

When I try installing it without bin/btoa.js with this command `npm install --no-bin-link btoa`, it works!

I'm assuming because of the bin/btoa.js I will have to use the --no-bin-link option but I don't know how to specify that in the package.json or I will have to globally install _all_ of my package.json dependencies which is silly.

There's no need for a bin/btoa.js. It isn't the equivalent of grunt, less, jshint or any other essential tasks. If you want to make it a command-line utility maybe create a separate package called `btoa-cmd` or something like that.

**Comment by coolaj86** [comment]
Although there isn't technically a need for a bin, I like having a little commandline ditty that anyone can use to test it out.

It looks like the problem you're having, however, is that node is installed incorrectly on your system. You'll probably come across many errors like this unless you fix that.

I'm not sure which system you're using, but if it's anything Ubuntu or Fedora or CentOS I believe it should be installed in a like manner to this:

``` bash
  NODE_VER="v0.11.14"

  # determine if this is a 32-bit or 64-bit machine
  if [ -n "$(arch | grep 64)" ]; then
    ARCH="x64"
  else
    ARCH="x86"
  fi

  echo "installing node ${NODE_VER}..."

  # download the installer to /tmp
  curl -fsSL "http://nodejs.org/dist/${NODE_VER}/node-${NODE_VER}-linux-${ARCH}.tar.gz" \
    -o "/tmp/node-${NODE_VER}-linux-${ARCH}.tar.gz"

  # extract and install the installer files
  pushd /tmp
  tar xf /tmp/node-${NODE_VER}-linux-${ARCH}.tar.gz
  rm node-${NODE_VER}-linux-x64/{LICENSE,ChangeLog,README.md}
  sudo rsync -a "/tmp/node-${NODE_VER}-linux-${ARCH}/" /usr/local/

  # change ownership of /usr/local to the current user
  sudo chown -R $(whoami) /usr/local
```

I also have a script that will do this for you: https://github.com/coolaj86/node-install-script

It should be installed to `/usr/local` (not `/usr`) and `/usr/local` should have the permissions of you user.

If you install via apt-get or yum or similar you'll get an old and out-of-date version and it will be installed to `/usr`, where your user won't be able to write.

**Comment by ghost** [comment]
@coolaj86 dudedudedudedude. Thank you that definitely helps a lot, I'm seeing errors in other packages when I'm doing npm install, awesome :+1:
